### ISSUE TITLE
CustomDropDown Bug

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#241]
### Overview
On android, the scroll for the menu does not work., but works fine with ios devices. Similarly, there are issue with ui where drop down menu is overlapping with others

### Task
- [x] Fix scrolling for custom drop down menu on android
- [x] Fix overlapping issue with drop down menu

**Comment by LucientZ** [comment]
This is related to how `ScrollView` is rendered on Android devices.

**Comment by LucientZ** [comment]
This bug is caused by using the "absolute" style in a parent component of the `ScrollView`. For whatever reason this causes the `ScrollView` component to not detect app gestures.
