### ISSUE TITLE
Add More Committee Icons

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#262]
### Overview
There are currently onl 3 icons committees. Add Various Icons that could possibility represents all the committee

### Task
- [x] Add more icons
- [x] Add option in the committee edit/create screen

### Additional
The reason why we're doing preset icons is because these icons are used in the event screen and committee screen, so dev must confirm in the icon fits before adding them. Also need to be svg and transparent.

**Comment by carolina367** [comment]
- once a committee is created, how can I edit or delete it from the app?
- clicking the representative memberCard leads to my own user card?
- pending request button is not formatted correctly
- why show rep/lead positions if no user is selected for those roles
- back button is very slow and takes multiple clicks
- joined committee and approved request, member count for committee didn't increase
