### ISSUE TITLE
Invovlement Tab Title

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#265]
### Overview
The invovlement tab label wraps to newline on small phones so it looks like:
(invovlemen
t)

### Task
- [ ] Fix text wrapping or rename tab.

**Comment by alvarojcamachoh** [comment]
[https://github.com/TAMUSHPE/MobileApp/commit/6c54be28c36bb7f53ef3cfa64d93df2f9e9f1848](url)

**Comment by alvarojcamachoh** [comment]
[https://github.com/TAMUSHPE/MobileApp/commit/6c54be28c36bb7f53ef3cfa64d93df2f9e9f1848](url)
