### ISSUE TITLE
Upload National/Chapter Doc Bug on Admin Screen

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#266]
###  Overview
When a user upload one document (i.e. only upload national). The approve/deny card for membership verification is display. However we only want to display approve/deny card if a user upload both documentation. Then an officer can approve/deny

### Task
- [ ] Display membership verification card for only users that upload both documents

**Comment by alvarojcamachoh** [comment]
[https://github.com/TAMUSHPE/MobileApp/commit/6193433c86c7ddd616553b7511ffb620b941c2b0](url)
