### ISSUE TITLE
Fix time formatting

### ISSUE THREAD

**Issue by mestrada03** [TAMUSHPE/MobileApp#296]
### Overview

"When choosing 12:30pm, it shows as "0:30pm" once event is created." - App Test User

[Screenshot](https://drive.google.com/open?id=1lvMlcJx2B15Evg0cu5-n1goYlvpzqTCJ)

### Task

- [x] Fix `formatTime` in `timeUtils.ts`

**Comment by LucientZ** [comment]
https://github.com/TAMUSHPE/MobileApp/pull/302
