### ISSUE TITLE
Event sign in/out high runtime

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#298]
### Overview
Event sign in/out loading time takes about 10-15 seconds. This needs to be a most 5 seconds.

### Task 
- [x] look into why runtime is so high
- [x] get user location only if event geolocation is turned on

### Additional
sign in/out use to be extremely fast, but during development in the past few weeks have caused a high runtime.

**Comment by JasonIsAzn** [comment]
the bottleneck for this function is cased by 
`
 const { status } = await Location.requestForegroundPermissionsAsync();
    let location: null | { longitude: number, latitude: number } = null;
    if (status == 'granted') {
        const { latitude, longitude } = (await Location.getCurrentPositionAsync()).coords;
        location = (new GeoPoint(latitude, longitude)).toJSON();
    } const { status } = await Location.requestForegroundPermissionsAsync();
    let location: null | { longitude: number, latitude: number } = null;
    if (status == 'granted') {
        const { latitude, longitude } = (await Location.getCurrentPositionAsync()).coords;
        location = (new GeoPoint(latitude, longitude)).toJSON();
    }
`
with the current implemntation a possible solution would be to either decrease accuracy causing the location percision to be +/- 100meter
or force users to scan QRCode using app's qrcode scanner so that we can get their location faster

**Comment by LucientZ** [comment]
What are the profiling stats on everything?
