### ISSUE TITLE
Account Email Verifcation

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#324]
### Overview
A guest account is required to login and allows a user to use any email. The email verification screen currently expect the user to leave the app and open it again. But also need to add a case when a user stay on the screen and confirm their email via another device.

### Task
- [ ] Add a loop to contantly check if email is verified

**Comment by Teja-11** [comment]
can i work on this?

**Comment by LucientZ** [comment]
Go right ahead.

**Comment by LucientZ** [comment]
Wait, actually who are you?
