### ISSUE TITLE
Lottie Animation Replacement

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#374]
### Overview
The splash screen takes too long to load and will begin to annoy users after lauching the app multiple times. Remove the splash screen and ensure that the transition into the app is smooth

### Task
- [x] Remove splash screen
- [x] Create checkmark animation to replace lottie animation
    - The current version of lottie has had a lot of issues with compatibility with between Android and iOS. Creating animations manually should give a more portable version of animations.

**Comment by LucientZ** [comment]
https://github.com/TAMUSHPE/MobileApp/pull/399
