### ISSUE TITLE
Dark/Light Mode sync with phone setting

### ISSUE THREAD

**Issue by JasonIsAzn** [TAMUSHPE/MobileApp#382]
### Overview
Implement dark and light mode to sync with phone settings

**Comment by LucientZ** [comment]
This should probably just take the phone setting on user creation and then keep that info in `privateUserInfo`. That way, if for whatever reason a user wants to change it to the other display mode, they can.

**Comment by JasonIsAzn** [comment]
ended up doing this:
[6f8704a](https://github.com/TAMUSHPE/MobileApp/pull/385/commits/6f8704a621d8cb6ed325f65fe8ef183020bfbd81)

But does require this which is a bit messy:
`
const userContext = useContext(UserContext);
const { userInfo } = userContext!;
const fixDarkMode = userInfo?.private?.privateInfo?.settings?.darkMode;
const useSystemDefault = userInfo?.private?.privateInfo?.settings?.useSystemDefault;
const colorScheme = useColorScheme();
const darkMode = useSystemDefault ? colorScheme === 'dark' : fixDarkMode;
`
