### ISSUE TITLE
Fix Padding Safe Area View on Android

### ISSUE THREAD

**Issue by mestrada03** [TAMUSHPE/MobileApp#420]
### Oveview
Padding on Android at the top has camera overlapping the images/text in some instances. Most notably on the home screen.

**Comment by JasonIsAzn** [comment]
Now that I'm looking at the padding for safe area view on android it looks similar to ios
So this shouldn't be a big deal.

Can look at this more later in #447  when doing ui changes. But don't need a whole ticket forthis
