### ISSUE TITLE
Low-Resolution phone support

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#447]
# Overview

Some phones that can run the app have screens that are too small to properly render everything. Resolutions like 480x800 are not currently fully supported by the app. Whenever a part of the UI is cut off, there's no way of scrolling down to the different components.

## Possible Fixes

This *could* be solved by simply putting `ScrollViews`everywhere, but there are some issues with putting nested ScrollViews (eg. android devices don't detect input if this is the case). This solution does work in most screen though, so it's probably fine for most cases.

Some components likely just need to have sizes that are based on the resolution of the screen rather than hard sizes.

# Screenshots

![image](https://github.com/user-attachments/assets/efed2e45-08a2-4f18-971e-a68a2e1285e3)
![image](https://github.com/user-attachments/assets/38f98200-9aae-4d74-82ff-6ed51599acd2)

**Comment by JasonIsAzn** [comment]
seems like there no current productive action/goal on this issue. 
We can reopen or open another ticket when we find more related issues.
