### ISSUE TITLE
Fix shaky test suite cleanup

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#450]
# Overview

Some test suites that were added actively delete collections inside the firebase emulator. The cleanup behavior needs to be removed/addressed as this can (and has) cause race conditions with other test suites.

This doesn't affect the app in any way, just our quality assurance (which is still important).

**Comment by JasonIsAzn** [comment]
chat i did it. i wrote the dam test cases

- #579
