### ISSUE TITLE
Refactor `getAttendanceNumber` to use aggregate queries instead of brute-force calculation

### ISSUE THREAD

**Issue by LucientZ** [TAMUSHPE/MobileApp#504]
# Overview
The function `getAttendanceNumber` in `firebaseUtils.ts` currently queries every signed-in user document in an event and counts how many have sign-in or sign-out times by iterating through each one. Not only does this waste computations due to the data not utilizing a firebase index, but reading each document individually is more expensive than simply using an aggregate query. 

Aggregate query documentation can be found [here](https://firebase.google.com/docs/firestore/query-data/aggregation-queries)

**Comment by JasonIsAzn** [comment]
81db1789ec89238e111df7d0475bb2cd1e8183f8
